#!/usr/bin/env python3
"""Assemble radar-only resources from the reviewed city radar catalogs."""

from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import struct
from dataclasses import dataclass
from pathlib import Path


REPOSITORY = Path(__file__).resolve().parents[2]
TEMPLATE = Path(__file__).with_name("native_world_radar_client.lua")
GRID_SIZE = 40
STOCK_RANGE = range(14, 26)
TILE_PATTERN = re.compile(
    r'^    \{ path = "(?P<path>[^"]+)", column = (?P<column>\d+), row = (?P<row>\d+), source = "(?P<source>[^"]*)" \},$'
)


@dataclass(frozen=True)
class ResourceSpec:
    pack_id: str
    display_name: str
    source_resource: str
    source_variable: str
    target_resource: str
    stats_command: str


@dataclass(frozen=True)
class RadarTile:
    path: str
    column: int
    row: int
    source: str


SPECS = (
    ResourceSpec("bullworth", "Bullworth", "ug-bw", "UG_BW_RADAR_TILES", "native-world-radar-bullworth", "nwradarbw"),
    ResourceSpec("vice-city", "Vice City", "ug-vc", "UG_VC_RADAR_TILES", "native-world-radar-vice-city", "nwradarvc"),
    ResourceSpec("liberty-city", "Liberty City", "ug-lc", "UG_LC_RADAR_TILES", "native-world-radar-liberty-city", "nwradarlc"),
    ResourceSpec("carcer-city", "Carcer City", "carcer-city-test", "CARCER_RADAR_TILES", "native-world-radar-carcer-city", "nwradarcc"),
)


def parse_catalog(path: Path, variable: str) -> list[RadarTile]:
    lines = path.read_text(encoding="utf-8").splitlines()
    try:
        start = lines.index(f"{variable} = {{")
    except ValueError as exc:
        raise ValueError(f"{path}: missing {variable}") from exc

    tiles: list[RadarTile] = []
    for line in lines[start + 1 :]:
        if line == "}":
            break
        match = TILE_PATTERN.fullmatch(line)
        if not match:
            raise ValueError(f"{path}: unsupported catalog line: {line!r}")
        tiles.append(
            RadarTile(
                path=match.group("path"),
                column=int(match.group("column")),
                row=int(match.group("row")),
                source=match.group("source"),
            )
        )
    else:
        raise ValueError(f"{path}: unterminated catalog")

    if not tiles:
        raise ValueError(f"{path}: empty catalog")
    return tiles


def validate_catalog(spec: ResourceSpec, tiles: list[RadarTile], occupied: dict[tuple[int, int], str]) -> None:
    paths: set[str] = set()
    for tile in tiles:
        expected_path = f"assets/radar/tile_{tile.column:02d}_{tile.row:02d}.txd"
        if tile.path != expected_path:
            raise ValueError(f"{spec.pack_id}: non-canonical tile path {tile.path!r}, expected {expected_path!r}")
        if not 0 <= tile.column < GRID_SIZE or not 0 <= tile.row < GRID_SIZE:
            raise ValueError(f"{spec.pack_id}: cell {tile.column},{tile.row} is outside the 40x40 grid")
        if tile.column in STOCK_RANGE and tile.row in STOCK_RANGE:
            raise ValueError(f"{spec.pack_id}: cell {tile.column},{tile.row} overlaps San Andreas")
        if tile.path in paths:
            raise ValueError(f"{spec.pack_id}: duplicate path {tile.path}")
        paths.add(tile.path)

        cell = (tile.column, tile.row)
        previous = occupied.get(cell)
        if previous:
            raise ValueError(f"{spec.pack_id}: cell {tile.column},{tile.row} overlaps {previous}")
        occupied[cell] = spec.pack_id


def catalog_text(spec: ResourceSpec, tiles: list[RadarTile]) -> str:
    lines = [
        "-- Generated by utils/extended-world/build_native_world_radar_resources.py.",
        "NATIVE_WORLD_RADAR_CATALOG = {",
        f'    packId = "{spec.pack_id}",',
        f'    displayName = "{spec.display_name}",',
        f'    statsCommand = "{spec.stats_command}",',
        "    tiles = {",
    ]
    for tile in tiles:
        lines.append(
            f'        {{ path = "{tile.path}", column = {tile.column}, row = {tile.row}, source = "{tile.source}" }},'
        )
    lines.extend(("    },", "}", ""))
    return "\n".join(lines)


def meta_text(spec: ResourceSpec, tiles: list[RadarTile]) -> str:
    lines = [
        "<meta>",
        f'    <info author="MTA Neon" name="Native world radar: {spec.display_name}" type="script" version="1.0.0" />',
        '    <script src="catalog.lua" type="client" cache="false" />',
        '    <script src="client.lua" type="client" cache="false" />',
        '    <export function="getNativeWorldRadarStatus" type="client" />',
        '    <export function="reloadNativeWorldRadar" type="client" />',
    ]
    lines.extend(f'    <file src="{tile.path}" />' for tile in tiles)
    lines.extend(("</meta>", ""))
    return "\n".join(lines)


def read_txd(path: Path) -> bytes:
    data = path.read_bytes()
    if len(data) < 12 or struct.unpack_from("<I", data)[0] != 0x16:
        raise ValueError(f"{path}: missing RenderWare texture-dictionary header")
    return data


def write_if_changed(path: Path, data: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(data, encoding="utf-8")


def assemble(repository: Path, verify: bool) -> list[tuple[ResourceSpec, list[RadarTile], int]]:
    template = TEMPLATE.read_text(encoding="utf-8")
    occupied: dict[tuple[int, int], str] = {}
    summaries: list[tuple[ResourceSpec, list[RadarTile], int]] = []

    for spec in SPECS:
        source_root = repository / "test-resources" / spec.source_resource
        target_root = repository / "test-resources" / spec.target_resource
        tiles = parse_catalog(source_root / "radar_tiles.lua", spec.source_variable)
        validate_catalog(spec, tiles, occupied)

        expected_files = {
            "catalog.lua": catalog_text(spec, tiles),
            "client.lua": template,
            "meta.xml": meta_text(spec, tiles),
        }
        for relative, expected in expected_files.items():
            target = target_root / relative
            if verify:
                if not target.exists() or target.read_text(encoding="utf-8") != expected:
                    raise ValueError(f"{target}: generated file is stale or missing")
            else:
                write_if_changed(target, expected)

        source_bytes = 0
        expected_asset_names = {Path(tile.path).name for tile in tiles}
        target_assets = target_root / "assets" / "radar"
        if not verify:
            target_assets.mkdir(parents=True, exist_ok=True)
            for stale in target_assets.glob("*.txd"):
                if stale.name not in expected_asset_names:
                    stale.unlink()

        for tile in tiles:
            source = source_root / tile.path
            data = read_txd(source)
            source_bytes += len(data)
            target = target_root / tile.path
            if verify:
                if not target.exists() or hashlib.sha256(target.read_bytes()).digest() != hashlib.sha256(data).digest():
                    raise ValueError(f"{target}: copied TXD is stale or missing")
            elif not target.exists() or hashlib.sha256(target.read_bytes()).digest() != hashlib.sha256(data).digest():
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source, target)

        summaries.append((spec, tiles, source_bytes))

    return summaries


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=REPOSITORY)
    parser.add_argument("--verify", action="store_true", help="check generated files and local TXD copies without writing")
    args = parser.parse_args()

    summaries = assemble(args.repo.resolve(), args.verify)
    action = "verified" if args.verify else "assembled"
    for spec, tiles, source_bytes in summaries:
        columns = [tile.column for tile in tiles]
        rows = [tile.row for tile in tiles]
        print(
            f"{action} {spec.pack_id}: {len(tiles)} tiles, "
            f"columns {min(columns)}..{max(columns)}, rows {min(rows)}..{max(rows)}, "
            f"{source_bytes / (1024 * 1024):.1f} MiB"
        )
    print(f"{action} {sum(len(tiles) for _, tiles, _ in summaries)} non-overlapping radar tiles")


if __name__ == "__main__":
    main()
