export const SETTING_IDS = [
  'extendedWorld.enabled',
  'extendedWorld.distance',
  'distantLights.enabled',
  'distantLights.distance',
  'distantLights.coronaSize',
  'skyGfx.enabled',
  'skyGfx.colorFilter',
  'skyGfx.colorFilterBlur',
  'skyGfx.pcTimecycle',
  'skyGfx.depthBias',
  'skyGfx.ycbcr',
  'skyGfx.radiosity',
  'skyGfx.radiosityIntensity',
  'skyGfx.radiosityFilterPasses',
  'skyGfx.radiosityRenderPasses',
  'radar.style',
  'radar.positionX',
  'radar.positionY',
  'radar.width',
  'radar.height',
  'radar.widescreenSafe',
  'graphics.videoMode',
  'graphics.displayMode',
  'graphics.fullscreenMinimize',
  'graphics.vsync',
  'graphics.dpiAware',
  'graphics.fov',
  'graphics.drawDistance',
  'graphics.brightness',
  'graphics.fxQuality',
  'graphics.anisotropic',
  'graphics.antiAliasing',
  'graphics.aspectRatio',
  'graphics.hudMatchAspectRatio',
  'graphics.volumetricShadows',
  'graphics.grass',
  'graphics.heatHaze',
  'graphics.tyreSmoke',
  'graphics.dynamicPedShadows',
  'graphics.motionBlur',
  'graphics.coronaReflections',
  'graphics.highDetailVehicles',
  'graphics.highDetailPeds',
  'graphics.showUnsafeResolutions',
  'graphics.deviceSelectionDialog',
  'graphics.gamma',
  'graphics.brightnessScale',
  'graphics.contrast',
  'graphics.saturation',
  'graphics.gammaEnabled',
  'graphics.brightnessEnabled',
  'graphics.contrastEnabled',
  'graphics.saturationEnabled',
  'graphics.applyWindowed',
  'graphics.applyFullscreen',
] as const

export type SettingId = typeof SETTING_IDS[number]
export type SettingValue = boolean | number
export type SettingValues = Record<SettingId, SettingValue>

interface SettingCopy {
  label: string
  description: string
}

// `satisfies Record<SettingId, ...>` is intentional. Adding a setting to
// the native contract without English help copy must fail the TypeScript build.
export const SETTINGS_COPY = {
  'extendedWorld.enabled': {
    label: 'Extended world distance',
    description: 'Extends GTA\'s far clip and stock-world model LOD range beyond the original game limit.',
  },
  'extendedWorld.distance': {
    label: 'World draw distance',
    description: 'Sets how far stock world geometry can remain visible. Higher values use more CPU, memory and GPU time.',
  },
  'distantLights.enabled': {
    label: 'Distant city lights',
    description: 'Enables Neon\'s integrated Project2DFX distant coronas so city lights remain visible from far away.',
  },
  'distantLights.distance': {
    label: 'Light draw distance',
    description: 'Sets the maximum range for Project2DFX distant lights. Large ranges can increase rendering cost.',
  },
  'distantLights.coronaSize': {
    label: 'Corona size',
    description: 'Scales the glow sprite around distant lights. This changes visual size, not the light draw range.',
  },
  'skyGfx.enabled': {
    label: 'Enable SkyGfx',
    description: 'Enables the optional MTA-controlled SkyGfx bridge and its integrated PlayStation 2 rendering effects.',
  },
  'skyGfx.colorFilter': {
    label: 'PS2 color filter',
    description: 'Applies the PlayStation 2 color-filter stage using GTA\'s current timecycle colors.',
  },
  'skyGfx.colorFilterBlur': {
    label: 'Soft filter blur',
    description: 'Softens the PS2 color filter before it is composited. Requires the PS2 color filter.',
  },
  'skyGfx.pcTimecycle': {
    label: 'Adapt PC timecycle colors',
    description: 'Adjusts PC timecycle values before the PS2 filter so the result stays closer to the console palette.',
  },
  'skyGfx.depthBias': {
    label: 'PS2 depth-bias precision',
    description: 'Uses PS2-style depth-bias behavior for supported rendering paths to reduce visual differences.',
  },
  'skyGfx.ycbcr': {
    label: 'Console YCbCr correction',
    description: 'Simulates the console video color range and chroma response used by the integrated SkyGfx pipeline.',
  },
  'skyGfx.radiosity': {
    label: 'PS2 radiosity glow',
    description: 'Adds the soft multi-pass glow associated with the PlayStation 2 version of GTA: San Andreas.',
  },
  'skyGfx.radiosityIntensity': {
    label: 'Glow intensity',
    description: 'Controls the strength threshold of the radiosity glow. PS2 Default is the balanced reference value.',
  },
  'skyGfx.radiosityFilterPasses': {
    label: 'Blur passes',
    description: 'Sets how many blur passes shape the radiosity buffer. More passes look softer and cost more GPU time.',
  },
  'skyGfx.radiosityRenderPasses': {
    label: 'Composite passes',
    description: 'Sets how many times the radiosity result is composited over the scene, increasing glow strength and cost.',
  },
  'radar.style': {
    label: 'Radar style',
    description: 'Chooses between GTA\'s original rectangular radar and Neon\'s integrated Definitive-style renderer.',
  },
  'radar.positionX': {
    label: 'Horizontal position',
    description: 'Sets the radar\'s left margin in GTA\'s 640-wide reference coordinate space.',
  },
  'radar.positionY': {
    label: 'Vertical position',
    description: 'Sets the radar\'s bottom margin in GTA\'s 448-high reference coordinate space.',
  },
  'radar.width': {
    label: 'Radar width',
    description: 'Sets the radar width in GTA reference pixels. Use a preset to restore a known-good shape.',
  },
  'radar.height': {
    label: 'Radar height',
    description: 'Sets the radar height in GTA reference pixels. Use a preset to restore a known-good shape.',
  },
  'radar.widescreenSafe': {
    label: 'Widescreen-safe sizing',
    description: 'Keeps the radar\'s apparent size stable instead of stretching it with widescreen aspect ratios.',
  },
  'graphics.videoMode': { label: 'Resolution', description: 'Sets the output resolution used by GTA. Unsafe modes are hidden unless explicitly shown.' },
  'graphics.displayMode': { label: 'Display mode', description: 'Chooses windowed, exclusive fullscreen or one of MTA\'s borderless presentation modes.' },
  'graphics.fullscreenMinimize': { label: 'Minimize fullscreen on focus loss', description: 'Minimizes fullscreen MTA when another window receives focus. This option is useful on multi-monitor systems.' },
  'graphics.vsync': { label: 'V-Sync', description: 'Synchronizes frame presentation with the display refresh rate to reduce tearing. It can also cap the effective frame rate.' },
  'graphics.dpiAware': { label: 'DPI-aware process', description: 'Uses native pixels on scaled Windows displays. This experimental option requires an MTA restart and can cause graphical issues.' },
  'graphics.fov': { label: 'Field of view', description: 'Controls the horizontal viewing angle. Wider values show more of the scene but make distant objects appear smaller.' },
  'graphics.drawDistance': { label: 'GTA draw distance', description: 'Controls the original GTA world draw distance. This is separate from Neon\'s extended-world range.' },
  'graphics.brightness': { label: 'Game brightness', description: 'Changes GTA\'s original brightness setting before optional display calibration is applied.' },
  'graphics.fxQuality': { label: 'Visual FX quality', description: 'Controls GTA particle and effect quality. Low disables grass and volumetric shadows; high unlocks dynamic ped shadows.' },
  'graphics.anisotropic': { label: 'Anisotropic filtering', description: 'Improves texture clarity at oblique viewing angles. Higher levels use more GPU filtering work.' },
  'graphics.antiAliasing': { label: 'Anti-aliasing', description: 'Smooths geometry edges using GTA\'s multisampling levels. Changing this setting requires an MTA restart.' },
  'graphics.aspectRatio': { label: 'Aspect ratio', description: 'Selects automatic detection or forces GTA\'s 4:3, 16:10 or 16:9 projection.' },
  'graphics.hudMatchAspectRatio': { label: 'HUD matches aspect ratio', description: 'Adjusts HUD placement and scaling to match the selected aspect ratio instead of using the original layout.' },
  'graphics.volumetricShadows': { label: 'Volumetric shadows', description: 'Enables GTA\'s heavier volumetric shadow effect. It can significantly reduce performance on some systems.' },
  'graphics.grass': { label: 'Grass effect', description: 'Renders GTA\'s world grass. It is unavailable when Visual FX Quality is set to Low.' },
  'graphics.heatHaze': { label: 'Heat haze', description: 'Enables distortion around hot surfaces and weather effects.' },
  'graphics.tyreSmoke': { label: 'Tyre smoke and particles', description: 'Enables tyre smoke and related vehicle particle effects.' },
  'graphics.dynamicPedShadows': { label: 'Dynamic ped shadows', description: 'Adds dynamic shadows to pedestrians. Requires High or Very High Visual FX Quality.' },
  'graphics.motionBlur': { label: 'Motion blur', description: 'Enables GTA\'s camera motion-blur effect during fast movement.' },
  'graphics.coronaReflections': { label: 'Corona rain reflections', description: 'Reflects light coronas on wet roads during rain.' },
  'graphics.highDetailVehicles': { label: 'Always high-detail vehicles', description: 'Keeps vehicle models at their highest detail for longer, increasing streaming and rendering cost.' },
  'graphics.highDetailPeds': { label: 'Always high-detail peds', description: 'Keeps pedestrian models at their highest detail for longer, increasing streaming and rendering cost.' },
  'graphics.showUnsafeResolutions': { label: 'Show unsafe resolutions', description: 'Includes modes larger than the current desktop or otherwise marked unsafe. They may make the interface unusable.' },
  'graphics.deviceSelectionDialog': { label: 'Device selection dialog', description: 'Shows the Direct3D device selection dialog during startup. Intended mainly for multi-monitor troubleshooting.' },
  'graphics.gamma': { label: 'Gamma', description: 'Adjusts mid-tone luminance in the calibrated presentation path without changing black and white points equally.' },
  'graphics.brightnessScale': { label: 'Brightness scale', description: 'Multiplies calibrated output brightness. This is separate from GTA\'s original brightness setting.' },
  'graphics.contrast': { label: 'Contrast', description: 'Changes the difference between darker and brighter tones in the calibrated output.' },
  'graphics.saturation': { label: 'Saturation', description: 'Changes color intensity in the calibrated output. 1.00x is neutral.' },
  'graphics.gammaEnabled': { label: 'Enable gamma adjustment', description: 'Enables the gamma value below when at least one calibration scope is active.' },
  'graphics.brightnessEnabled': { label: 'Enable brightness adjustment', description: 'Enables the brightness scale below when at least one calibration scope is active.' },
  'graphics.contrastEnabled': { label: 'Enable contrast adjustment', description: 'Enables the contrast value below when at least one calibration scope is active.' },
  'graphics.saturationEnabled': { label: 'Enable saturation adjustment', description: 'Enables the saturation value below when at least one calibration scope is active.' },
  'graphics.applyWindowed': { label: 'Apply in windowed and borderless', description: 'Applies display calibration to windowed and borderless presentation modes.' },
  'graphics.applyFullscreen': { label: 'Apply in exclusive fullscreen', description: 'Applies display calibration while using exclusive fullscreen presentation.' },
} satisfies Record<SettingId, SettingCopy>

export const DEFAULT_SETTINGS: SettingValues = {
  'extendedWorld.enabled': false,
  'extendedWorld.distance': 2000,
  'distantLights.enabled': false,
  'distantLights.distance': 2000,
  'distantLights.coronaSize': 0.25,
  'skyGfx.enabled': true,
  'skyGfx.colorFilter': true,
  'skyGfx.colorFilterBlur': false,
  'skyGfx.pcTimecycle': true,
  'skyGfx.depthBias': true,
  'skyGfx.ycbcr': true,
  'skyGfx.radiosity': false,
  'skyGfx.radiosityIntensity': 35,
  'skyGfx.radiosityFilterPasses': 2,
  'skyGfx.radiosityRenderPasses': 1,
  'radar.style': 0,
  'radar.positionX': 40,
  'radar.positionY': 104,
  'radar.width': 85.5,
  'radar.height': 78,
  'radar.widescreenSafe': true,
  'graphics.videoMode': 0,
  'graphics.displayMode': 1,
  'graphics.fullscreenMinimize': false,
  'graphics.vsync': true,
  'graphics.dpiAware': false,
  'graphics.fov': 70,
  'graphics.drawDistance': 31,
  'graphics.brightness': 66,
  'graphics.fxQuality': 2,
  'graphics.anisotropic': 0,
  'graphics.antiAliasing': 1,
  'graphics.aspectRatio': 0,
  'graphics.hudMatchAspectRatio': true,
  'graphics.volumetricShadows': false,
  'graphics.grass': true,
  'graphics.heatHaze': false,
  'graphics.tyreSmoke': true,
  'graphics.dynamicPedShadows': false,
  'graphics.motionBlur': false,
  'graphics.coronaReflections': false,
  'graphics.highDetailVehicles': false,
  'graphics.highDetailPeds': false,
  'graphics.showUnsafeResolutions': false,
  'graphics.deviceSelectionDialog': true,
  'graphics.gamma': 0.95,
  'graphics.brightnessScale': 1.03,
  'graphics.contrast': 1,
  'graphics.saturation': 1,
  'graphics.gammaEnabled': false,
  'graphics.brightnessEnabled': false,
  'graphics.contrastEnabled': false,
  'graphics.saturationEnabled': false,
  'graphics.applyWindowed': false,
  'graphics.applyFullscreen': false,
}
