export const SETTING_IDS = [
  'game.nickname',
  'game.savePasswords',
  'game.autoRefreshBrowser',
  'game.allowScreenUpload',
  'game.allowExternalSounds',
  'game.alwaysShowTransferBox',
  'game.discordRichPresence',
  'game.discordShareData',
  'game.steamStatus',
  'game.saveCameraPhotos',
  'game.askBeforeDisconnect',
  'game.customizedSAFiles',
  'game.mapOpacity',
  'game.mapImage',
  'audio.masterVolume',
  'audio.radioVolume',
  'audio.sfxVolume',
  'audio.mtaVolume',
  'audio.voiceVolume',
  'audio.radioEqualizer',
  'audio.radioAutotune',
  'audio.userTrackAutoScan',
  'audio.userTrackMode',
  'audio.muteMaster',
  'audio.muteRadio',
  'audio.muteSfx',
  'audio.muteMta',
  'audio.muteVoice',
  'controls.invertMouse',
  'controls.steerWithMouse',
  'controls.flyWithMouse',
  'controls.mouseSensitivity',
  'controls.verticalAimSensitivity',
  'controls.useMouseSensitivityForAiming',
  'controls.classicControls',
  'controls.joypadDeadZone',
  'controls.joypadSaturation',
  'interface.locale',
  'interface.skin',
  'interface.chatBackgroundColor',
  'interface.chatTextColor',
  'interface.chatInputBackgroundColor',
  'interface.chatInputTextColor',
  'interface.chatFont',
  'interface.chatLines',
  'interface.chatScaleX',
  'interface.chatScaleY',
  'interface.chatWidth',
  'interface.chatCssText',
  'interface.chatCssBackground',
  'interface.chatNickCompletion',
  'interface.chatTextOutline',
  'interface.chatLineLife',
  'interface.chatLineFadeOut',
  'interface.chatPositionHorizontal',
  'interface.chatPositionVertical',
  'interface.chatTextAlignment',
  'interface.chatOffsetX',
  'interface.chatOffsetY',
  'interface.flashWindow',
  'interface.trayNotifications',
  'browser.remoteWebsites',
  'browser.remoteJavascript',
  'browser.gpuRendering',
  'browser.videoAcceleration',
  'advanced.fastClothesLoading',
  'advanced.browserSpeed',
  'advanced.singleConnection',
  'advanced.packetTag',
  'advanced.progressAnimation',
  'advanced.processPriority',
  'advanced.debugSetting',
  'advanced.streamingMemory',
  'advanced.cpuAffinity',
  'advanced.updateBuildType',
  'advanced.updateAutoInstall',
  'extendedWorld.enabled',
  'extendedWorld.distance',
  'distantLights.enabled',
  'distantLights.searchlights',
  'distantLights.autoDistance',
  'distantLights.growWithDistance',
  'distantLights.nearAlpha',
  'distantLights.reachFullAlpha',
  'distantLights.boostStart',
  'distantLights.farAlphaBoost',
  'distantLights.distance',
  'distantLights.coronaSize',
  'skyGfx.enabled',
  'skyGfx.colorFilter',
  'skyGfx.colorFilterBlur',
  'skyGfx.pcTimecycle',
  'skyGfx.depthBias',
  'skyGfx.ycbcr',
  'skyGfx.radiosity',
  'skyGfx.radiosityIntensity',
  'skyGfx.radiosityFilterPasses',
  'skyGfx.radiosityRenderPasses',
  'radar.style',
  'radar.positionX',
  'radar.positionY',
  'radar.width',
  'radar.height',
  'radar.widescreenSafe',
  'graphics.videoMode',
  'graphics.displayMode',
  'graphics.fullscreenMinimize',
  'graphics.vsync',
  'graphics.dpiAware',
  'graphics.fov',
  'graphics.drawDistance',
  'graphics.brightness',
  'graphics.fxQuality',
  'graphics.anisotropic',
  'graphics.antiAliasing',
  'graphics.aspectRatio',
  'graphics.hudMatchAspectRatio',
  'graphics.volumetricShadows',
  'graphics.grass',
  'graphics.heatHaze',
  'graphics.tyreSmoke',
  'graphics.dynamicPedShadows',
  'graphics.motionBlur',
  'graphics.coronaReflections',
  'graphics.highDetailVehicles',
  'graphics.highDetailPeds',
  'graphics.showUnsafeResolutions',
  'graphics.deviceSelectionDialog',
  'graphics.gamma',
  'graphics.brightnessScale',
  'graphics.contrast',
  'graphics.saturation',
  'graphics.gammaEnabled',
  'graphics.brightnessEnabled',
  'graphics.contrastEnabled',
  'graphics.saturationEnabled',
  'graphics.applyWindowed',
  'graphics.applyFullscreen',
] as const

export type SettingId = typeof SETTING_IDS[number]
export type SettingValue = boolean | number | string
export type SettingValues = Record<SettingId, SettingValue>

interface SettingCopy {
  label: string
  description: string
}

// `satisfies Record<SettingId, ...>` is intentional. Adding a setting to
// the native contract without English help copy must fail the TypeScript build.
export const SETTINGS_COPY = {
  'game.nickname': { label: 'Nickname', description: 'Sets the player name shown to servers and other players. MTA validates it before applying changes.' },
  'game.savePasswords': { label: 'Remember server passwords', description: 'Stores passwords used for protected servers. Turning this off also clears passwords already saved by the server browser.' },
  'game.autoRefreshBrowser': { label: 'Refresh servers automatically', description: 'Refreshes the selected server list whenever the server browser opens.' },
  'game.allowScreenUpload': { label: 'Allow screenshot uploads', description: 'Allows a server to request and upload screenshots for anti-cheat or administration. The chat box and MTA interface are excluded from captures.' },
  'game.allowExternalSounds': { label: 'Allow external sounds', description: 'Allows servers to play audio loaded from external internet addresses. Only enable this for servers you trust.' },
  'game.alwaysShowTransferBox': { label: 'Always show transfer progress', description: 'Keeps the resource-download progress interface visible even when a server script tries to hide it.' },
  'game.discordRichPresence': { label: 'Discord Rich Presence', description: 'Shares the current MTA menu or server activity with the local Discord client.' },
  'game.discordShareData': { label: 'Share Discord data with servers', description: 'Allows connected servers to receive your Discord client ID and game-state information. Discord Rich Presence itself can remain enabled without this permission.' },
  'game.steamStatus': { label: 'Steam game status', description: 'Connects to the local Steam client so GTA: San Andreas can appear as the active game.' },
  'game.saveCameraPhotos': { label: 'Save camera photos', description: 'Saves photos taken with GTA\'s camera weapon inside your Windows Documents folder.' },
  'game.askBeforeDisconnect': { label: 'Confirm before disconnecting', description: 'Shows a confirmation before leaving the current server from the main menu.' },
  'game.customizedSAFiles': { label: 'Use customized GTA files', description: 'Allows supported modified GTA files. Changing this option requires an MTA restart and may affect server compatibility.' },
  'game.mapOpacity': { label: 'Map opacity', description: 'Controls the opacity of the full-screen player map.' },
  'game.mapImage': { label: 'Map image quality', description: 'Chooses the standard or higher-detail image used by the full-screen player map.' },
  'audio.masterVolume': { label: 'Master volume', description: 'Controls the final level of every GTA, MTA and voice sound.' },
  'audio.radioVolume': { label: 'Radio volume', description: 'Controls GTA radio and user-track playback before master volume is applied.' },
  'audio.sfxVolume': { label: 'Sound effects volume', description: 'Controls GTA world, vehicle and weapon sounds before master volume is applied.' },
  'audio.mtaVolume': { label: 'MTA sound volume', description: 'Controls sounds played by MTA resources through the client audio system.' },
  'audio.voiceVolume': { label: 'Voice chat volume', description: 'Controls the playback level of other players using MTA voice chat.' },
  'audio.radioEqualizer': { label: 'Radio equalizer', description: 'Uses GTA\'s radio equalizer effect while music is playing.' },
  'audio.radioAutotune': { label: 'Radio auto-retune', description: 'Automatically resumes the appropriate radio station when entering vehicles.' },
  'audio.userTrackAutoScan': { label: 'Scan user tracks automatically', description: 'Automatically scans GTA San Andreas User Tracks when the game starts.' },
  'audio.userTrackMode': { label: 'User-track play mode', description: 'Chooses whether custom tracks behave like a radio station, play randomly or play sequentially.' },
  'audio.muteMaster': { label: 'Mute all when minimized', description: 'Mutes every game and MTA audio channel while the window is minimized.' },
  'audio.muteRadio': { label: 'Mute radio when minimized', description: 'Mutes only GTA radio and user tracks while the window is minimized.' },
  'audio.muteSfx': { label: 'Mute SFX when minimized', description: 'Mutes only GTA world and sound effects while the window is minimized.' },
  'audio.muteMta': { label: 'Mute MTA sounds when minimized', description: 'Mutes sounds created by MTA resources while the window is minimized.' },
  'audio.muteVoice': { label: 'Mute voice when minimized', description: 'Mutes player voice chat while the window is minimized.' },
  'controls.invertMouse': { label: 'Invert mouse vertically', description: 'Reverses the vertical mouse axis used by the GTA camera.' },
  'controls.steerWithMouse': { label: 'Steer with mouse', description: 'Uses horizontal mouse movement to steer supported ground vehicles.' },
  'controls.flyWithMouse': { label: 'Fly with mouse', description: 'Uses mouse movement to control aircraft.' },
  'controls.mouseSensitivity': { label: 'Mouse sensitivity', description: 'Controls horizontal GTA camera and aiming sensitivity.' },
  'controls.verticalAimSensitivity': { label: 'Vertical aim sensitivity', description: 'Controls vertical aiming independently when linked sensitivity is disabled.' },
  'controls.useMouseSensitivityForAiming': { label: 'Link aiming sensitivity', description: 'Uses the main mouse sensitivity value for vertical aiming instead of the separate value.' },
  'controls.classicControls': { label: 'Classic joypad controls', description: 'Switches GTA from standard mouse-and-keyboard controls to its classic joypad control scheme.' },
  'controls.joypadDeadZone': { label: 'Joypad dead zone', description: 'Ignores small movements around the center of a controller axis. Increase it if a stick drifts.' },
  'controls.joypadSaturation': { label: 'Joypad saturation', description: 'Sets how far an axis must move before it reaches maximum input.' },
  'interface.locale': { label: 'Language', description: 'Changes the MTA interface language. It cannot be changed while connected to a server.' },
  'interface.skin': { label: 'Legacy interface skin', description: 'Chooses the skin used by remaining native CEGUI windows and dialogs.' },
  'interface.chatBackgroundColor': { label: 'Chat background color', description: 'Sets the chat history background color and transparency.' },
  'interface.chatTextColor': { label: 'Chat text color', description: 'Sets the default chat history text color and opacity.' },
  'interface.chatInputBackgroundColor': { label: 'Chat input background', description: 'Sets the background color and transparency of the chat input field.' },
  'interface.chatInputTextColor': { label: 'Chat input text', description: 'Sets the text color and opacity used while typing chat messages.' },
  'interface.chatFont': { label: 'Chat font', description: 'Chooses one of the four fonts supported by the native MTA chat box.' },
  'interface.chatLines': { label: 'Visible chat lines', description: 'Sets how many lines remain visible in the chat history.' },
  'interface.chatScaleX': { label: 'Horizontal chat scale', description: 'Scales chat text and layout horizontally.' },
  'interface.chatScaleY': { label: 'Vertical chat scale', description: 'Scales chat text and layout vertically.' },
  'interface.chatWidth': { label: 'Chat width', description: 'Sets the width available to chat lines before wrapping.' },
  'interface.chatCssText': { label: 'CSS-style chat text', description: 'Enables the alternative styled-text rendering supported by MTA chat.' },
  'interface.chatCssBackground': { label: 'Hide idle chat background', description: 'Hides the chat background while you are not typing.' },
  'interface.chatNickCompletion': { label: 'Tab nickname completion', description: 'Lets the Tab key complete player nicknames while typing a chat message.' },
  'interface.chatTextOutline': { label: 'Chat text outline', description: 'Adds a contrasting black or white outline around chat text.' },
  'interface.chatLineLife': { label: 'Message lifetime', description: 'Sets how many seconds a chat line remains fully visible.' },
  'interface.chatLineFadeOut': { label: 'Message fade duration', description: 'Sets how many seconds a chat line takes to fade out.' },
  'interface.chatPositionHorizontal': { label: 'Horizontal chat anchor', description: 'Anchors the chat box to the left or right side of the screen.' },
  'interface.chatPositionVertical': { label: 'Vertical chat anchor', description: 'Anchors the chat box to the top or bottom of the screen.' },
  'interface.chatTextAlignment': { label: 'Chat text alignment', description: 'Aligns chat text against the left or right edge of the chat box.' },
  'interface.chatOffsetX': { label: 'Horizontal chat offset', description: 'Moves the chat box horizontally from its selected screen anchor.' },
  'interface.chatOffsetY': { label: 'Vertical chat offset', description: 'Moves the chat box vertically from its selected screen anchor.' },
  'interface.flashWindow': { label: 'Allow window flashing', description: 'Allows servers to request attention by flashing the MTA taskbar button.' },
  'interface.trayNotifications': { label: 'Allow tray notifications', description: 'Allows scripts to create Windows tray balloon notifications.' },
  'browser.remoteWebsites': { label: 'Enable remote websites', description: 'Allows server resources to load approved web content from the internet.' },
  'browser.remoteJavascript': { label: 'JavaScript on remote websites', description: 'Allows JavaScript to run on remote web pages opened by MTA resources.' },
  'browser.gpuRendering': { label: 'Browser GPU rendering', description: 'Enables hardware rendering for CEF content such as WebGL. Changing it requires an MTA restart.' },
  'browser.videoAcceleration': { label: 'Browser video acceleration', description: 'Enables hardware video decoding in CEF. Changing it requires an MTA restart.' },
  'advanced.fastClothesLoading': { label: 'Fast CJ clothes loading', description: 'Controls MTA\'s optimized loading path for CJ clothing. Auto is recommended.' },
  'advanced.browserSpeed': { label: 'Server-browser scan speed', description: 'Controls how aggressively the legacy browser sends server queries. Faster scanning uses more network activity.' },
  'advanced.singleConnection': { label: 'Single download connection', description: 'Forces resource downloads to use one connection for compatibility with some networks.' },
  'advanced.packetTag': { label: 'Packet tag', description: 'Adds diagnostic tags to network packets. Leave this at Default unless troubleshooting.' },
  'advanced.progressAnimation': { label: 'Progress animation', description: 'Controls the progress spinner shown at the bottom of the game screen.' },
  'advanced.processPriority': { label: 'Process priority', description: 'Changes the Windows scheduling priority of MTA. High priority can reduce responsiveness of other applications.' },
  'advanced.debugSetting': { label: 'Diagnostic mode', description: 'Enables an internal diagnostic mode. Leave this at Default unless a developer asks for a specific option.' },
  'advanced.streamingMemory': { label: 'Streaming memory', description: 'Sets the memory budget used by GTA world streaming within the safe range detected by MTA.' },
  'advanced.cpuAffinity': { label: 'Exclude CPU 0', description: 'Moves MTA away from CPU 0 to avoid contention seen on some systems.' },
  'advanced.updateBuildType': { label: 'Update channel', description: 'Chooses the stable or nightly MTA update channel.' },
  'advanced.updateAutoInstall': { label: 'Install important updates', description: 'Allows the updater to install important updates automatically.' },
  'extendedWorld.enabled': {
    label: 'Extended world distance',
    description: 'Extends GTA\'s far clip and stock-world model LOD range beyond the original game limit.',
  },
  'extendedWorld.distance': {
    label: 'World draw distance',
    description: 'Sets how far stock world geometry can remain visible. Higher values use more CPU, memory and GPU time.',
  },
  'distantLights.enabled': {
    label: 'Distant city lights',
    description: 'Enables Neon\'s integrated Project2DFX distant coronas so city lights remain visible from far away.',
  },
  'distantLights.searchlights': {
    label: 'Light beams',
    description: 'Shows light beams beneath supported streetlights at night. Requires distant city lights.',
  },
  'distantLights.autoDistance': {
    label: 'Automatic light range',
    description: 'Follows the current world view distance, including weather and server overrides.',
  },
  'distantLights.growWithDistance': {
    label: 'Grow halos with distance',
    description: 'Gradually enlarges distant halos, matching Project2DFX.',
  },
  'distantLights.nearAlpha': {
    label: 'Near brightness',
    description: 'Starting brightness multiplier for the distance curve.',
  },
  'distantLights.reachFullAlpha': {
    label: 'Full brightness distance',
    description: 'Distance from the start of the halo transition to normal brightness, in metres.',
  },
  'distantLights.boostStart': {
    label: 'Brightness boost distance',
    description: 'Distance from the start of the transition where the extra brightness boost begins, in metres.',
  },
  'distantLights.farAlphaBoost': {
    label: 'Far brightness multiplier',
    description: 'Maximum distance-based brightness multiplier.',
  },
  'distantLights.distance': {
    label: 'Light draw distance',
    description: 'Sets the maximum range for Project2DFX distant lights. Large ranges can increase rendering cost.',
  },
  'distantLights.coronaSize': {
    label: 'Corona size',
    description: 'Scales the glow sprite around distant lights. This changes visual size, not the light draw range.',
  },
  'skyGfx.enabled': {
    label: 'Enable SkyGfx',
    description: 'Enables the optional MTA-controlled SkyGfx bridge and its integrated PlayStation 2 rendering effects.',
  },
  'skyGfx.colorFilter': {
    label: 'PS2 color filter',
    description: 'Applies the PlayStation 2 color-filter stage using GTA\'s current timecycle colors.',
  },
  'skyGfx.colorFilterBlur': {
    label: 'Soft filter blur',
    description: 'Softens the PS2 color filter before it is composited. Requires the PS2 color filter.',
  },
  'skyGfx.pcTimecycle': {
    label: 'Adapt PC timecycle colors',
    description: 'Adjusts PC timecycle values before the PS2 filter so the result stays closer to the console palette.',
  },
  'skyGfx.depthBias': {
    label: 'PS2 depth-bias precision',
    description: 'Uses PS2-style depth-bias behavior for supported rendering paths to reduce visual differences.',
  },
  'skyGfx.ycbcr': {
    label: 'Console YCbCr correction',
    description: 'Simulates the console video color range and chroma response used by the integrated SkyGfx pipeline.',
  },
  'skyGfx.radiosity': {
    label: 'PS2 radiosity glow',
    description: 'Adds the soft multi-pass glow associated with the PlayStation 2 version of GTA: San Andreas.',
  },
  'skyGfx.radiosityIntensity': {
    label: 'Glow intensity',
    description: 'Controls the strength threshold of the radiosity glow. PS2 Default is the balanced reference value.',
  },
  'skyGfx.radiosityFilterPasses': {
    label: 'Blur passes',
    description: 'Sets how many blur passes shape the radiosity buffer. More passes look softer and cost more GPU time.',
  },
  'skyGfx.radiosityRenderPasses': {
    label: 'Composite passes',
    description: 'Sets how many times the radiosity result is composited over the scene, increasing glow strength and cost.',
  },
  'radar.style': {
    label: 'Radar style',
    description: 'Chooses between GTA\'s original rectangular radar and Neon\'s integrated Definitive-style renderer.',
  },
  'radar.positionX': {
    label: 'Horizontal position',
    description: 'Sets the radar\'s left margin in GTA\'s 640-wide reference coordinate space.',
  },
  'radar.positionY': {
    label: 'Vertical position',
    description: 'Sets the radar\'s bottom margin in GTA\'s 448-high reference coordinate space.',
  },
  'radar.width': {
    label: 'Radar width',
    description: 'Sets the radar width in GTA reference pixels. Use a preset to restore a known-good shape.',
  },
  'radar.height': {
    label: 'Radar height',
    description: 'Sets the radar height in GTA reference pixels. Use a preset to restore a known-good shape.',
  },
  'radar.widescreenSafe': {
    label: 'Widescreen-safe sizing',
    description: 'Keeps the radar\'s apparent size stable instead of stretching it with widescreen aspect ratios.',
  },
  'graphics.videoMode': { label: 'Resolution', description: 'Sets the output resolution used by GTA. Unsafe modes are hidden unless explicitly shown.' },
  'graphics.displayMode': { label: 'Display mode', description: 'Chooses windowed, exclusive fullscreen or one of MTA\'s borderless presentation modes.' },
  'graphics.fullscreenMinimize': { label: 'Minimize fullscreen on focus loss', description: 'Minimizes fullscreen MTA when another window receives focus. This option is useful on multi-monitor systems.' },
  'graphics.vsync': { label: 'V-Sync', description: 'Synchronizes frame presentation with the display refresh rate to reduce tearing. It can also cap the effective frame rate.' },
  'graphics.dpiAware': { label: 'DPI-aware process', description: 'Uses native pixels on scaled Windows displays. This experimental option requires an MTA restart and can cause graphical issues.' },
  'graphics.fov': { label: 'Field of view', description: 'Controls the horizontal viewing angle. Wider values show more of the scene but make distant objects appear smaller.' },
  'graphics.drawDistance': { label: 'GTA draw distance', description: 'Controls the original GTA world draw distance. This is separate from Neon\'s extended-world range.' },
  'graphics.brightness': { label: 'Game brightness', description: 'Changes GTA\'s original brightness setting before optional display calibration is applied.' },
  'graphics.fxQuality': { label: 'Visual FX quality', description: 'Controls GTA particle and effect quality. Low disables grass and volumetric shadows; high unlocks dynamic ped shadows.' },
  'graphics.anisotropic': { label: 'Anisotropic filtering', description: 'Improves texture clarity at oblique viewing angles. Higher levels use more GPU filtering work.' },
  'graphics.antiAliasing': { label: 'Anti-aliasing', description: 'Smooths geometry edges using GTA\'s multisampling levels. Changing this setting requires an MTA restart.' },
  'graphics.aspectRatio': { label: 'Aspect ratio', description: 'Selects automatic detection or forces GTA\'s 4:3, 16:10 or 16:9 projection.' },
  'graphics.hudMatchAspectRatio': { label: 'HUD matches aspect ratio', description: 'Adjusts HUD placement and scaling to match the selected aspect ratio instead of using the original layout.' },
  'graphics.volumetricShadows': { label: 'Volumetric shadows', description: 'Enables GTA\'s heavier volumetric shadow effect. It can significantly reduce performance on some systems.' },
  'graphics.grass': { label: 'Grass effect', description: 'Renders GTA\'s world grass. It is unavailable when Visual FX Quality is set to Low.' },
  'graphics.heatHaze': { label: 'Heat haze', description: 'Enables distortion around hot surfaces and weather effects.' },
  'graphics.tyreSmoke': { label: 'Tyre smoke and particles', description: 'Enables tyre smoke and related vehicle particle effects.' },
  'graphics.dynamicPedShadows': { label: 'Dynamic ped shadows', description: 'Adds dynamic shadows to pedestrians. Requires High or Very High Visual FX Quality.' },
  'graphics.motionBlur': { label: 'Motion blur', description: 'Enables GTA\'s camera motion-blur effect during fast movement.' },
  'graphics.coronaReflections': { label: 'Corona rain reflections', description: 'Reflects light coronas on wet roads during rain.' },
  'graphics.highDetailVehicles': { label: 'Always high-detail vehicles', description: 'Keeps vehicle models at their highest detail for longer, increasing streaming and rendering cost.' },
  'graphics.highDetailPeds': { label: 'Always high-detail peds', description: 'Keeps pedestrian models at their highest detail for longer, increasing streaming and rendering cost.' },
  'graphics.showUnsafeResolutions': { label: 'Show unsafe resolutions', description: 'Includes modes larger than the current desktop or otherwise marked unsafe. They may make the interface unusable.' },
  'graphics.deviceSelectionDialog': { label: 'Device selection dialog', description: 'Shows the Direct3D device selection dialog during startup. Intended mainly for multi-monitor troubleshooting.' },
  'graphics.gamma': { label: 'Gamma', description: 'Adjusts mid-tone luminance in the calibrated presentation path without changing black and white points equally.' },
  'graphics.brightnessScale': { label: 'Brightness scale', description: 'Multiplies calibrated output brightness. This is separate from GTA\'s original brightness setting.' },
  'graphics.contrast': { label: 'Contrast', description: 'Changes the difference between darker and brighter tones in the calibrated output.' },
  'graphics.saturation': { label: 'Saturation', description: 'Changes color intensity in the calibrated output. 1.00x is neutral.' },
  'graphics.gammaEnabled': { label: 'Enable gamma adjustment', description: 'Enables the gamma value below when at least one calibration scope is active.' },
  'graphics.brightnessEnabled': { label: 'Enable brightness adjustment', description: 'Enables the brightness scale below when at least one calibration scope is active.' },
  'graphics.contrastEnabled': { label: 'Enable contrast adjustment', description: 'Enables the contrast value below when at least one calibration scope is active.' },
  'graphics.saturationEnabled': { label: 'Enable saturation adjustment', description: 'Enables the saturation value below when at least one calibration scope is active.' },
  'graphics.applyWindowed': { label: 'Apply in windowed and borderless', description: 'Applies display calibration to windowed and borderless presentation modes.' },
  'graphics.applyFullscreen': { label: 'Apply in exclusive fullscreen', description: 'Applies display calibration while using exclusive fullscreen presentation.' },
} satisfies Record<SettingId, SettingCopy>

export const DEFAULT_SETTINGS: SettingValues = {
  'game.nickname': 'Player',
  'game.savePasswords': true,
  'game.autoRefreshBrowser': true,
  'game.allowScreenUpload': true,
  'game.allowExternalSounds': true,
  'game.alwaysShowTransferBox': false,
  'game.discordRichPresence': true,
  'game.discordShareData': false,
  'game.steamStatus': false,
  'game.saveCameraPhotos': false,
  'game.askBeforeDisconnect': true,
  'game.customizedSAFiles': false,
  'game.mapOpacity': 61,
  'game.mapImage': 0,
  'audio.masterVolume': 100,
  'audio.radioVolume': 100,
  'audio.sfxVolume': 100,
  'audio.mtaVolume': 100,
  'audio.voiceVolume': 100,
  'audio.radioEqualizer': true,
  'audio.radioAutotune': true,
  'audio.userTrackAutoScan': false,
  'audio.userTrackMode': 0,
  'audio.muteMaster': false,
  'audio.muteRadio': false,
  'audio.muteSfx': false,
  'audio.muteMta': false,
  'audio.muteVoice': false,
  'controls.invertMouse': false,
  'controls.steerWithMouse': false,
  'controls.flyWithMouse': false,
  'controls.mouseSensitivity': 50,
  'controls.verticalAimSensitivity': 50,
  'controls.useMouseSensitivityForAiming': false,
  'controls.classicControls': false,
  'controls.joypadDeadZone': 15,
  'controls.joypadSaturation': 100,
  'interface.locale': 'en_US',
  'interface.skin': 'Default',
  'interface.chatBackgroundColor': 0,
  'interface.chatTextColor': 4289517054,
  'interface.chatInputBackgroundColor': 0,
  'interface.chatInputTextColor': 4289517054,
  'interface.chatFont': 2,
  'interface.chatLines': 10,
  'interface.chatScaleX': 1,
  'interface.chatScaleY': 1,
  'interface.chatWidth': 1.5,
  'interface.chatCssText': false,
  'interface.chatCssBackground': false,
  'interface.chatNickCompletion': true,
  'interface.chatTextOutline': false,
  'interface.chatLineLife': 12,
  'interface.chatLineFadeOut': 3,
  'interface.chatPositionHorizontal': 0,
  'interface.chatPositionVertical': 0,
  'interface.chatTextAlignment': 0,
  'interface.chatOffsetX': 0.0125,
  'interface.chatOffsetY': 0.015,
  'interface.flashWindow': true,
  'interface.trayNotifications': true,
  'browser.remoteWebsites': true,
  'browser.remoteJavascript': true,
  'browser.gpuRendering': true,
  'browser.videoAcceleration': true,
  'advanced.fastClothesLoading': 1,
  'advanced.browserSpeed': 1,
  'advanced.singleConnection': 0,
  'advanced.packetTag': 0,
  'advanced.progressAnimation': 1,
  'advanced.processPriority': 0,
  'advanced.debugSetting': 0,
  'advanced.streamingMemory': 50,
  'advanced.cpuAffinity': true,
  'advanced.updateBuildType': 0,
  'advanced.updateAutoInstall': 1,
  'extendedWorld.enabled': false,
  'extendedWorld.distance': 2000,
  'distantLights.enabled': false,
  'distantLights.searchlights': true,
  'distantLights.autoDistance': true,
  'distantLights.growWithDistance': true,
  'distantLights.nearAlpha': 0.5,
  'distantLights.reachFullAlpha': 150,
  'distantLights.boostStart': 150,
  'distantLights.farAlphaBoost': 4,
  'distantLights.distance': 2000,
  'distantLights.coronaSize': 0.25,
  'skyGfx.enabled': true,
  'skyGfx.colorFilter': true,
  'skyGfx.colorFilterBlur': false,
  'skyGfx.pcTimecycle': true,
  'skyGfx.depthBias': true,
  'skyGfx.ycbcr': true,
  'skyGfx.radiosity': false,
  'skyGfx.radiosityIntensity': 35,
  'skyGfx.radiosityFilterPasses': 2,
  'skyGfx.radiosityRenderPasses': 1,
  'radar.style': 0,
  'radar.positionX': 40,
  'radar.positionY': 104,
  'radar.width': 85.5,
  'radar.height': 78,
  'radar.widescreenSafe': true,
  'graphics.videoMode': 0,
  'graphics.displayMode': 1,
  'graphics.fullscreenMinimize': false,
  'graphics.vsync': true,
  'graphics.dpiAware': false,
  'graphics.fov': 70,
  'graphics.drawDistance': 31,
  'graphics.brightness': 66,
  'graphics.fxQuality': 2,
  'graphics.anisotropic': 0,
  'graphics.antiAliasing': 1,
  'graphics.aspectRatio': 0,
  'graphics.hudMatchAspectRatio': true,
  'graphics.volumetricShadows': false,
  'graphics.grass': true,
  'graphics.heatHaze': false,
  'graphics.tyreSmoke': true,
  'graphics.dynamicPedShadows': false,
  'graphics.motionBlur': false,
  'graphics.coronaReflections': false,
  'graphics.highDetailVehicles': false,
  'graphics.highDetailPeds': false,
  'graphics.showUnsafeResolutions': false,
  'graphics.deviceSelectionDialog': true,
  'graphics.gamma': 0.95,
  'graphics.brightnessScale': 1.03,
  'graphics.contrast': 1,
  'graphics.saturation': 1,
  'graphics.gammaEnabled': false,
  'graphics.brightnessEnabled': false,
  'graphics.contrastEnabled': false,
  'graphics.saturationEnabled': false,
  'graphics.applyWindowed': false,
  'graphics.applyFullscreen': false,
}
