from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .jsonio import sha256_bytes, write_json


HEADER = """---@meta
-- Generated by MTA Neon. Do not edit by hand.
-- Signatures come from pinned MTA/Neon documentation; opaque remains unknown.
---@diagnostic disable: lowercase-global, duplicate-set-field

"""


TYPE_ALIASES = {
    "bool": "boolean",
    "boolean": "boolean",
    "int": "integer",
    "uint": "integer",
    "float": "number",
    "double": "number",
    "number": "number",
    "var": "any",
    "mixed": "any",
    "unknown": "unknown",
    "xmlnode": "xmlnode",
}

LUA_RESERVED = {
    "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if", "in", "local",
    "nil", "not", "or", "repeat", "return", "then", "true", "until", "while",
}


def _lua_identifier(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9_]", "_", value.strip())
    if not normalized or normalized[0].isdigit():
        normalized = f"mta_{normalized}"
    if normalized in LUA_RESERVED:
        normalized += "_"
    return normalized


def _lua_field(value: str) -> str:
    return value if re.fullmatch(r"[A-Za-z_]\w*", value) and value not in LUA_RESERVED else f"[{json.dumps(value, ensure_ascii=False)}]"


def _lua_type(value: str) -> str:
    value = value.strip()
    if not value:
        return "any"
    parts = re.split(r"\s*[|/]\s*", value)
    rendered: list[str] = []
    for part in parts:
        token = part.strip()
        lowered = token.casefold()
        if lowered in ("false", "true", "nil", "string", "table", "function", "thread", "userdata", "any"):
            candidate = lowered
        elif lowered in TYPE_ALIASES:
            candidate = TYPE_ALIASES[lowered]
        elif token.endswith("[]"):
            candidate = f"{_lua_type(token[:-2])}[]"
        elif re.fullmatch(r"table\s*<.*>", token):
            candidate = "table"
        elif re.fullmatch(r"[A-Za-z_][A-Za-z0-9_-]*", token):
            candidate = _lua_identifier(token)
        else:
            candidate = "any"
        if candidate not in rendered:
            rendered.append(candidate)
    return "|".join(rendered) if rendered else "any"


def _one_line(value: str) -> str:
    return " ".join(value.replace("\r", "").splitlines()).strip()


def _contracts_for(symbol: dict, side: str, profile: str) -> list[dict]:
    contracts = symbol.get("contracts", [])
    candidates = [contract for contract in contracts if contract.get("side") in (side, "shared")]
    return sorted(
        candidates,
        key=lambda contract: (
            0 if contract.get("provider") == ("mta" if profile == "mta-upstream" else "neon") else 1,
            0 if contract.get("side") == side else 1,
            contract.get("sourcePath", ""),
        ),
    )


def _primary_contract(symbol: dict, side: str, profile: str) -> dict:
    contracts = _contracts_for(symbol, side, profile)
    if contracts:
        return contracts[0]
    return {"parameters": symbol.get("parameters", []), "returns": symbol.get("returns", [])}


def _symbol_sides(symbol: dict, profile: str) -> set[str]:
    sides = set(symbol.get("inheritedSides", [])) if profile == "mta-upstream" else set(symbol.get("sides", []))
    if profile == "neon-server":
        sides.discard("client")
    elif profile == "neon-client":
        sides.discard("server")
    return sides


def _shared_safe(symbol: dict, profile: str) -> bool:
    if _symbol_sides(symbol, profile) != {"client", "server"}:
        return False
    contracts = symbol.get("contracts", [])
    if any(contract.get("side") == "shared" for contract in contracts):
        return True
    client = _primary_contract(symbol, "client", profile)
    server = _primary_contract(symbol, "server", profile)
    return client.get("parameters") == server.get("parameters") and client.get("returns") == server.get("returns")


def _render_symbol(symbol: dict, side: str, profile: str) -> str:
    contract = _primary_contract(symbol, side, profile)
    lines = []
    description = contract.get("description") or symbol.get("description")
    if description:
        lines.append(f"--- {_one_line(description)}")
    restriction = " Restricted API." if symbol.get("restricted") else ""
    lines.append(f"--- `{symbol['id']}` ({symbol['state']}).{restriction}")
    if symbol.get("state") == "runtime-only":
        lines.append("---@param ... unknown # Signature is opaque; no arity is asserted.")
        lines.append("---@return unknown")
        lines.append(f"function {symbol['name']}(...) end")
        return "\n".join(lines) + "\n\n"
    parameters = contract.get("parameters", [])
    if not parameters:
        parameters = symbol.get("parameters", [])
    for parameter in parameters:
        name = parameter.get("name", "arg")
        if name == "...":
            name = "..."
        else:
            name = _lua_identifier(name)
            if parameter.get("optional"):
                name += "?"
        comment = _one_line(parameter.get("description", ""))
        suffix = f" # {comment}" if comment else ""
        lines.append(f"---@param {name} {_lua_type(parameter.get('type', 'unknown'))}{suffix}")
    returns = contract.get("returns", [])
    if not returns:
        returns = symbol.get("returns", [])
    for returned in returns:
        comment = _one_line(returned.get("description", "") or contract.get("returnDescription", ""))
        suffix = f" # {comment}" if comment else ""
        name = returned.get("name")
        name_suffix = f" {name}" if name and re.fullmatch(r"[A-Za-z_]\w*", name) else ""
        lines.append(f"---@return {_lua_type(returned.get('type', 'unknown'))}{name_suffix}{suffix}")
    if not returns:
        lines.append("---@return nil")
    lines.append(f"function {symbol['name']}(...) end")
    return "\n".join(lines) + "\n\n"


def _render_classes(catalogue: dict) -> str:
    classes = []
    seen: set[str] = set()
    builtin_types = {"any", "boolean", "function", "integer", "nil", "number", "string", "table", "thread", "userdata"}
    for symbol in catalogue.get("symbols", []):
        if symbol.get("kind") not in ("element", "type"):
            continue
        name = _lua_identifier(symbol["name"])
        if name.casefold() in builtin_types or symbol.get("kind") == "type" and _lua_type(symbol["name"]) in builtin_types:
            continue
        if name in seen:
            continue
        seen.add(name)
        base = ": element" if symbol.get("kind") == "element" and name != "element" else ""
        classes.append(f"---@class {name}{base}\n")
    return "".join(classes) + ("\n" if classes else "")


def _member_sides(member: dict[str, Any], profile: str) -> set[str]:
    return set(member.get("inheritedSides", [])) if profile == "mta-upstream" else set(member.get("sides", []))


def _global_member_symbol(functions: dict[str, dict[str, Any]], member: dict[str, Any], side: str, profile: str) -> dict[str, Any] | None:
    binding_field = "inheritedBindings" if profile == "mta-upstream" else "bindings"
    names = [binding["globalFunction"] for binding in member.get(binding_field, []) if binding.get("side") == side and binding.get("globalFunction")]
    return next((functions[name] for name in names if name in functions), None)


def _render_oop_method(functions: dict[str, dict[str, Any]], class_name: str, member: dict[str, Any], side: str, profile: str) -> str:
    name = member["name"]
    if not re.fullmatch(r"[A-Za-z_]\w*", name) or name in LUA_RESERVED:
        return f"---@field {_lua_field(name)} fun(...: unknown): unknown\n"
    global_symbol = _global_member_symbol(functions, member, side, profile)
    if global_symbol is None or global_symbol.get("state") in ("conflict", "documented-only", "unavailable", "runtime-only"):
        return f"---@param ... unknown # OOP binding has no safe semantic signature.\n---@return unknown\nfunction {class_name}:{name}(...) end\n\n"
    contract = _primary_contract(global_symbol, side, profile)
    oop = contract.get("oop", {})
    static_method = oop.get("constructorClass") == class_name
    instance_method = oop.get("method") == name
    for legacy in contract.get("oopMethods", []):
        if re.match(rf"^\s*{re.escape(class_name)}\.{re.escape(name)}\s*\(", legacy):
            static_method = True
        elif re.match(rf"^\s*[A-Za-z_]\w*:{re.escape(name)}\s*\(", legacy):
            instance_method = True
    if not static_method and not instance_method:
        return f"---@param ... unknown # OOP/global binding semantics are unresolved.\n---@return unknown\nfunction {class_name}:{name}(...) end\n\n"
    parameters = list(contract.get("parameters", []))
    if instance_method and parameters:
        parameters = parameters[1:]
    lines = [f"--- Global binding: `{global_symbol['id']}` ({global_symbol['state']})."]
    for parameter in parameters:
        parameter_name = _lua_identifier(parameter.get("name", "arg")) + ("?" if parameter.get("optional") else "")
        lines.append(f"---@param {parameter_name} {_lua_type(parameter.get('type', 'unknown'))}")
    for returned in contract.get("returns", []):
        lines.append(f"---@return {_lua_type(returned.get('type', 'unknown'))}")
    if not contract.get("returns"):
        lines.append("---@return nil")
    separator = "." if static_method else ":"
    lines.append(f"function {class_name}{separator}{name}(...) end")
    return "\n".join(lines) + "\n\n"


def _property_type(functions: dict[str, dict[str, Any]], member: dict[str, Any], side: str, profile: str) -> str:
    binding_field = "inheritedBindings" if profile == "mta-upstream" else "bindings"
    names = [binding["getter"] for binding in member.get(binding_field, []) if binding.get("side") == side and binding.get("getter")]
    types: list[str] = []
    for name in names:
        symbol = functions.get(name)
        if symbol is None or symbol.get("state") in ("conflict", "documented-only", "unavailable", "runtime-only"):
            continue
        contract = _primary_contract(symbol, side, profile)
        for value in contract.get("returns", [])[:1]:
            rendered = _lua_type(value.get("type", "unknown"))
            if rendered not in types:
                types.append(rendered)
    return "|".join(types) if types else "unknown"


def _render_oop_classes(catalogue: dict[str, Any], side: str, profile: str) -> str:
    blocks: list[str] = []
    functions = {symbol["name"]: symbol for symbol in catalogue.get("symbols", []) if symbol.get("kind") == "function"}
    parents_field = "inheritedParents" if profile == "mta-upstream" else "parents"
    for symbol in sorted((item for item in catalogue.get("symbols", []) if item.get("kind") == "class"), key=lambda item: item["name"]):
        if side not in _symbol_sides(symbol, profile):
            continue
        class_name = _lua_identifier(symbol["name"])
        parents = symbol.get(parents_field, [])
        parent = f": {_lua_identifier(parents[0])}" if parents else ""
        lines = [f"--- `{symbol['id']}` ({symbol['state']}); members follow exact {side} registrations.\n", f"---@class {class_name}{parent}\n"]
        for member in symbol.get("properties", []):
            if side in _member_sides(member, profile):
                binding_field = "inheritedBindings" if profile == "mta-upstream" else "bindings"
                bindings = [binding for binding in member.get(binding_field, []) if binding.get("side") == side]
                readable = any(binding.get("getter") or binding.get("nativeGetter") for binding in bindings)
                writable = any(binding.get("setter") or binding.get("nativeSetter") for binding in bindings)
                access = " # read-only" if readable and not writable else " # write-only; readable type is unknown" if writable and not readable else ""
                lines.append(f"---@field {_lua_field(member['name'])} {_property_type(functions, member, side, profile)}{access}\n")
        lines.append(f"{class_name} = {class_name} or {{}}\n\n")
        for member in symbol.get("methods", []):
            if side in _member_sides(member, profile):
                lines.append(_render_oop_method(functions, class_name, member, side, profile))
        blocks.append("".join(lines))
    return "".join(blocks)


def render_luals(catalogue: dict, side: str, profile: str = "neon-pair") -> str:
    symbols = []
    for symbol in catalogue.get("symbols", []):
        if symbol.get("kind") != "function" or symbol.get("state") in ("unavailable", "documented-only", "conflict"):
            continue
        sides = _symbol_sides(symbol, profile)
        if side == "shared" and _shared_safe(symbol, profile):
            symbols.append(symbol)
        elif side in ("client", "server") and side in sides and not _shared_safe(symbol, profile):
            symbols.append(symbol)
    symbols.sort(key=lambda symbol: (symbol["name"].casefold(), symbol["name"]))
    classes = _render_classes(catalogue) if side == "shared" else _render_oop_classes(catalogue, side, profile)
    return (HEADER + classes + "".join(_render_symbol(symbol, side, profile) for symbol in symbols)).rstrip() + "\n"


def generate_luals(catalogue: dict, output_directory: Path, profile: str = "neon-pair") -> dict:
    output_directory.mkdir(parents=True, exist_ok=True)
    artifacts: list[dict] = []
    for side in ("shared", "client", "server"):
        payload = render_luals(catalogue, side, profile).encode("utf-8")
        path = output_directory / f"mta-{side}.lua"
        path.write_bytes(payload)
        artifacts.append(
            {
                "schemaVersion": "1.0.0",
                "id": f"neon:artifact:luals-{side}",
                "kind": "luals",
                "path": path.name,
                "mediaType": "text/x-lua",
                "size": len(payload),
                "sha256": sha256_bytes(payload),
            }
        )
    index = {"schemaVersion": "1.0.0", "artifacts": artifacts}
    write_json(output_directory / "artifacts.json", index)
    return index


def _render_local_callable(symbol: dict[str, Any], target: str, method: bool = False) -> str:
    lines = [f"--- {symbol['description']}", f"--- `{symbol['id']}` ({symbol['state']})."]
    if not symbol.get("signatureKnown", False):
        lines.extend(("---@param ... unknown # Signature is opaque; no arity is asserted.", "---@return unknown"))
    else:
        for parameter in symbol.get("parameters", []):
            name = _lua_identifier(parameter["name"]) + ("?" if parameter.get("optional") else "")
            description = _one_line(parameter.get("description", ""))
            lines.append(f"---@param {name} {_lua_type(parameter.get('type', 'unknown'))}" + (f" # {description}" if description else ""))
        for returned in symbol.get("returns", []):
            description = _one_line(returned.get("description", ""))
            lines.append(f"---@return {_lua_type(returned.get('type', 'unknown'))}" + (f" # {description}" if description else ""))
        if not symbol.get("returns"):
            lines.append("---@return nil")
    separator = ":" if method else "."
    lines.append(f"function {target}{separator}{symbol['name']}(...) end")
    return "\n".join(lines) + "\n\n"


def render_project_luals(symbols: list[dict[str, Any]], side: str) -> str:
    selected = [symbol for symbol in symbols if side in _component_sides_for_luals(symbol.get("side", "shared"))]
    selected.sort(key=lambda symbol: symbol["id"])
    lines = [HEADER]
    module_functions = [symbol for symbol in selected if symbol.get("ownerKind") == "module" and symbol.get("kind") == "function"]
    for symbol in module_functions:
        lines.append(_render_local_callable(symbol, "_G", method=False).replace(f"function _G.{symbol['name']}", f"function {symbol['name']}"))

    resource_exports = [symbol for symbol in selected if symbol.get("ownerKind") == "resource" and symbol.get("kind") == "export"]
    owners = sorted({symbol["owner"] for symbol in resource_exports})
    if owners:
        lines.append("---@class neon_project_exports\n")
        for owner in owners:
            lines.append(f"---@field {_lua_field(owner)} neon_exports_{_lua_identifier(owner)}_{side}\n")
        lines.append("---@type neon_project_exports\nexports = exports\n\n")
    for owner in owners:
        class_name = f"neon_exports_{_lua_identifier(owner)}_{side}"
        lines.append(f"---@class {class_name}\nlocal {class_name} = {{}}\n\n")
        for symbol in resource_exports:
            if symbol["owner"] == owner:
                lines.append(_render_local_callable(symbol, class_name, method=True))

    events = [symbol for symbol in selected if symbol.get("kind") == "event"]
    if events:
        values = "|".join(f'\"{symbol["name"]}\"' for symbol in events)
        lines.append(f"---@alias neon_{side}_event_name {values}\n")
    elements = [symbol for symbol in selected if symbol.get("kind") == "element"]
    for symbol in elements:
        lines.append(f"---@class {_lua_identifier(symbol['name'])}: element\n")
    return "".join(lines).rstrip() + "\n"


def _component_sides_for_luals(side: str) -> tuple[str, ...]:
    return ("client", "server") if side == "shared" else (side,)
