from __future__ import annotations

import re
from pathlib import Path

from .jsonio import sha256_bytes, write_json


HEADER = """---@meta
-- Generated by MTA Neon. Do not edit by hand.
-- Signatures come from pinned MTA/Neon documentation; unknown remains any.
---@diagnostic disable: lowercase-global, duplicate-set-field

"""


TYPE_ALIASES = {
    "bool": "boolean",
    "boolean": "boolean",
    "int": "integer",
    "uint": "integer",
    "float": "number",
    "double": "number",
    "number": "number",
    "var": "any",
    "mixed": "any",
    "unknown": "any",
    "xmlnode": "xmlnode",
}


def _lua_identifier(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9_]", "_", value.strip())
    if not normalized or normalized[0].isdigit():
        normalized = f"mta_{normalized}"
    return normalized


def _lua_type(value: str) -> str:
    value = value.strip()
    if not value:
        return "any"
    parts = re.split(r"\s*[|/]\s*", value)
    rendered: list[str] = []
    for part in parts:
        token = part.strip()
        lowered = token.casefold()
        if lowered in ("false", "true", "nil", "string", "table", "function", "thread", "userdata", "any"):
            candidate = lowered
        elif lowered in TYPE_ALIASES:
            candidate = TYPE_ALIASES[lowered]
        elif token.endswith("[]"):
            candidate = f"{_lua_type(token[:-2])}[]"
        elif re.fullmatch(r"table\s*<.*>", token):
            candidate = "table"
        elif re.fullmatch(r"[A-Za-z_][A-Za-z0-9_-]*", token):
            candidate = _lua_identifier(token)
        else:
            candidate = "any"
        if candidate not in rendered:
            rendered.append(candidate)
    return "|".join(rendered) if rendered else "any"


def _one_line(value: str) -> str:
    return " ".join(value.replace("\r", "").splitlines()).strip()


def _contracts_for(symbol: dict, side: str) -> list[dict]:
    contracts = symbol.get("contracts", [])
    candidates = [contract for contract in contracts if contract.get("side") in (side, "shared")]
    return sorted(
        candidates,
        key=lambda contract: (
            0 if contract.get("provider") == "neon" else 1,
            0 if contract.get("side") == side else 1,
            contract.get("sourcePath", ""),
        ),
    )


def _primary_contract(symbol: dict, side: str) -> dict:
    contracts = _contracts_for(symbol, side)
    if contracts:
        return contracts[0]
    return {"parameters": symbol.get("parameters", []), "returns": symbol.get("returns", [])}


def _shared_safe(symbol: dict) -> bool:
    if set(symbol.get("sides", [])) != {"client", "server"}:
        return False
    contracts = symbol.get("contracts", [])
    if any(contract.get("side") == "shared" for contract in contracts):
        return True
    client = _primary_contract(symbol, "client")
    server = _primary_contract(symbol, "server")
    return client.get("parameters") == server.get("parameters") and client.get("returns") == server.get("returns")


def _render_symbol(symbol: dict, side: str) -> str:
    contract = _primary_contract(symbol, side)
    lines = []
    description = contract.get("description") or symbol.get("description")
    if description:
        lines.append(f"--- {_one_line(description)}")
    restriction = " Restricted API." if symbol.get("restricted") else ""
    lines.append(f"--- `{symbol['id']}` ({symbol['state']}).{restriction}")
    parameters = contract.get("parameters", [])
    if not parameters:
        parameters = symbol.get("parameters", [])
    for parameter in parameters:
        name = parameter.get("name", "arg")
        if name == "...":
            name = "..."
        else:
            name = _lua_identifier(name)
            if parameter.get("optional"):
                name += "?"
        comment = _one_line(parameter.get("description", ""))
        suffix = f" # {comment}" if comment else ""
        lines.append(f"---@param {name} {_lua_type(parameter.get('type', 'unknown'))}{suffix}")
    returns = contract.get("returns", [])
    if not returns:
        returns = symbol.get("returns", [])
    for returned in returns:
        comment = _one_line(returned.get("description", "") or contract.get("returnDescription", ""))
        suffix = f" # {comment}" if comment else ""
        name = returned.get("name")
        name_suffix = f" {name}" if name and re.fullmatch(r"[A-Za-z_]\w*", name) else ""
        lines.append(f"---@return {_lua_type(returned.get('type', 'unknown'))}{name_suffix}{suffix}")
    if not returns:
        lines.append("---@return nil")
    lines.append(f"function {symbol['name']}(...) end")
    return "\n".join(lines) + "\n\n"


def _render_classes(catalogue: dict) -> str:
    classes = []
    seen: set[str] = set()
    builtin_types = {"any", "boolean", "function", "integer", "nil", "number", "string", "table", "thread", "userdata"}
    for symbol in catalogue.get("symbols", []):
        if symbol.get("kind") not in ("element", "type"):
            continue
        name = _lua_identifier(symbol["name"])
        if name.casefold() in builtin_types or symbol.get("kind") == "type" and _lua_type(symbol["name"]) in builtin_types:
            continue
        if name in seen:
            continue
        seen.add(name)
        base = ": element" if symbol.get("kind") == "element" and name != "element" else ""
        classes.append(f"---@class {name}{base}\n")
    return "".join(classes) + ("\n" if classes else "")


def render_luals(catalogue: dict, side: str) -> str:
    symbols = []
    for symbol in catalogue.get("symbols", []):
        if symbol.get("kind") != "function" or symbol.get("state") in ("unavailable", "documented-only"):
            continue
        sides = set(symbol.get("sides", []))
        if side == "shared" and _shared_safe(symbol):
            symbols.append(symbol)
        elif side in ("client", "server") and side in sides and not _shared_safe(symbol):
            symbols.append(symbol)
    symbols.sort(key=lambda symbol: (symbol["name"].casefold(), symbol["name"]))
    classes = _render_classes(catalogue) if side == "shared" else ""
    return (HEADER + classes + "".join(_render_symbol(symbol, side) for symbol in symbols)).rstrip() + "\n"


def generate_luals(catalogue: dict, output_directory: Path) -> dict:
    output_directory.mkdir(parents=True, exist_ok=True)
    artifacts: list[dict] = []
    for side in ("shared", "client", "server"):
        payload = render_luals(catalogue, side).encode("utf-8")
        path = output_directory / f"mta-{side}.lua"
        path.write_bytes(payload)
        artifacts.append(
            {
                "schemaVersion": "1.0.0",
                "id": f"neon:artifact:luals-{side}",
                "kind": "luals",
                "path": path.name,
                "mediaType": "text/x-lua",
                "size": len(payload),
                "sha256": sha256_bytes(payload),
            }
        )
    index = {"schemaVersion": "1.0.0", "artifacts": artifacts}
    write_json(output_directory / "artifacts.json", index)
    return index
