from __future__ import annotations

from pathlib import Path

from .jsonio import sha256_bytes, write_json


HEADER = """---@meta
-- Generated by MTA Neon. Do not edit by hand.
-- Unknown signatures are deliberately typed as unknown instead of guessed.
---@diagnostic disable: lowercase-global, duplicate-set-field

"""


def _render_symbol(symbol: dict) -> str:
    restriction = " Restricted API." if symbol.get("restricted") else ""
    return (
        f"--- `{symbol['id']}` ({symbol['state']}).{restriction}\n"
        "---@param ... unknown\n"
        "---@return unknown\n"
        f"function {symbol['name']}(...) end\n\n"
    )


def render_luals(catalogue: dict, side: str) -> str:
    symbols = []
    for symbol in catalogue.get("symbols", []):
        if symbol.get("kind") != "function" or symbol.get("state") == "unavailable":
            continue
        sides = set(symbol.get("sides", []))
        if side == "shared" and sides == {"client", "server"}:
            symbols.append(symbol)
        elif side in ("client", "server") and sides == {side}:
            symbols.append(symbol)
    symbols.sort(key=lambda symbol: (symbol["name"].casefold(), symbol["name"]))
    return (HEADER + "".join(_render_symbol(symbol) for symbol in symbols)).rstrip() + "\n"


def generate_luals(catalogue: dict, output_directory: Path) -> dict:
    output_directory.mkdir(parents=True, exist_ok=True)
    artifacts: list[dict] = []
    for side in ("shared", "client", "server"):
        payload = render_luals(catalogue, side).encode("utf-8")
        path = output_directory / f"mta-{side}.lua"
        path.write_bytes(payload)
        artifacts.append(
            {
                "schemaVersion": "1.0.0",
                "id": f"neon:artifact:luals-{side}",
                "kind": "luals",
                "path": path.name,
                "mediaType": "text/x-lua",
                "size": len(payload),
                "sha256": sha256_bytes(payload),
            }
        )
    index = {"schemaVersion": "1.0.0", "artifacts": artifacts}
    write_json(output_directory / "artifacts.json", index)
    return index
